"""Generate a DOCX business plan using python-docx.

Produces a Word document with styles, section headings, and optional
watermark footer on free-tier previews.
"""

from __future__ import annotations

import io

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Inches, Pt, RGBColor

ACCENT_COLOR = RGBColor(0x63, 0x66, 0xF1)
GRAY_COLOR = RGBColor(0x9C, 0xA3, 0xAF)

SECTION_ORDER = [
    "executive_summary",
    "market_analysis",
    "competitive_landscape",
    "operations",
    "financials",
    "consistency",
]

SECTION_TITLES = {
    "executive_summary":     "Executive Summary",
    "market_analysis":       "Market Analysis",
    "competitive_landscape": "Competitive Landscape",
    "operations":            "Operations Plan",
    "financials":            "Financial Projections",
    "consistency":           "Summary",
    "preview":               "Executive Summary Preview",
}


def render_docx(
    *,
    title: str,
    sections: dict[str, str],
    is_preview: bool = False,
    generated_for: str = "",
) -> bytes:
    """Return DOCX bytes for a business plan."""

    doc = Document()

    # ── Page margins ──────────────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin = Inches(1.1)
        section.bottom_margin = Inches(1.1)
        section.left_margin = Inches(1.25)
        section.right_margin = Inches(1.25)

    # ── Cover ─────────────────────────────────────────────────────────────
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title_para.runs:
        run.font.color.rgb = ACCENT_COLOR
        run.font.size = Pt(28)

    if generated_for:
        p = doc.add_paragraph(f"Prepared for: {generated_for}")
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in p.runs:
            run.font.color.rgb = GRAY_COLOR
            run.font.size = Pt(11)

    if is_preview:
        warn = doc.add_paragraph(
            "⚠ PREVIEW — Subscribe at build-block.com for the full plan."
        )
        warn.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in warn.runs:
            run.font.color.rgb = ACCENT_COLOR
            run.font.size = Pt(10)
            run.bold = True

    branding = doc.add_paragraph("Generated by Build-Block · build-block.com")
    branding.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in branding.runs:
        run.font.color.rgb = GRAY_COLOR
        run.font.size = Pt(9)

    doc.add_page_break()

    # ── Sections ──────────────────────────────────────────────────────────
    ordered_keys = [k for k in SECTION_ORDER if k in sections]
    ordered_keys += [k for k in sections if k not in ordered_keys]

    for key in ordered_keys:
        text = sections[key]
        if not text or not text.strip():
            continue

        section_title = SECTION_TITLES.get(key, key.replace("_", " ").title())
        heading = doc.add_heading(section_title, level=1)
        for run in heading.runs:
            run.font.color.rgb = ACCENT_COLOR

        for para in text.split("\n\n"):
            para = para.strip()
            if not para:
                continue
            p = doc.add_paragraph(para.replace("\n", " "))
            p.paragraph_format.space_after = Pt(8)
            p.paragraph_format.line_spacing = Pt(16)

    # ── Watermark footer on preview ───────────────────────────────────────
    if is_preview:
        _add_watermark_footer(doc)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _add_watermark_footer(doc: Document) -> None:
    for section in doc.sections:
        footer = section.footer
        p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        p.clear()
        run = p.add_run("PREVIEW — Build-Block · Not for redistribution")
        run.font.size = Pt(8)
        run.font.color.rgb = GRAY_COLOR
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
