"""Generate a PDF business plan using ReportLab.

Produces a professional, clean document with a cover page,
section headers, and body text. Watermarks free-tier previews.
"""

from __future__ import annotations

import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)
from reportlab.platypus.flowables import Flowable

BRAND_DARK = colors.HexColor("#0a0a0f")
BRAND_ACCENT = colors.HexColor("#6366f1")
BRAND_LIGHT = colors.HexColor("#e4e4ef")
BRAND_GRAY = colors.HexColor("#9ca3af")
WATERMARK_GRAY = colors.HexColor("#d1d5db")

SECTION_ORDER = [
    "executive_summary",
    "market_analysis",
    "competitive_landscape",
    "operations",
    "financials",
    "consistency",
]

SECTION_TITLES = {
    "executive_summary":    "Executive Summary",
    "market_analysis":      "Market Analysis",
    "competitive_landscape": "Competitive Landscape",
    "operations":           "Operations Plan",
    "financials":           "Financial Projections",
    "consistency":          "Summary",
    "preview":              "Executive Summary Preview",
}


class _WatermarkCanvas:
    """Mixin that adds a diagonal watermark to every page."""

    def __init__(self, *args, watermark_text: str = "", **kwargs):
        from reportlab.pdfgen import canvas as pdfcanvas
        self._watermark = watermark_text
        super().__init__(*args, **kwargs)

    def showPage(self):
        if self._watermark:
            self.saveState()
            self.setFont("Helvetica", 52)
            self.setFillColor(WATERMARK_GRAY, alpha=0.18)
            self.translate(LETTER[0] / 2, LETTER[1] / 2)
            self.rotate(40)
            self.drawCentredString(0, 0, self._watermark)
            self.restoreState()
        super().showPage()


def _make_canvas_class(watermark: str):
    from reportlab.pdfgen.canvas import Canvas

    class WatermarkedCanvas(Canvas):
        def showPage(self):
            if watermark:
                self.saveState()
                self.setFont("Helvetica", 52)
                self.setFillColor(WATERMARK_GRAY, alpha=0.18)
                self.translate(LETTER[0] / 2, LETTER[1] / 2)
                self.rotate(40)
                self.drawCentredString(0, 0, watermark)
                self.restoreState()
            super().showPage()

    return WatermarkedCanvas


def render_pdf(
    *,
    title: str,
    sections: dict[str, str],
    is_preview: bool = False,
    generated_for: str = "",
) -> bytes:
    """Return PDF bytes for a business plan."""

    buf = io.BytesIO()
    watermark = "PREVIEW — Build-Block" if is_preview else ""

    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        leftMargin=1.1 * inch,
        rightMargin=1.1 * inch,
        topMargin=1.0 * inch,
        bottomMargin=1.0 * inch,
    )

    styles = getSampleStyleSheet()
    cover_title = ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontSize=28,
        textColor=BRAND_ACCENT,
        spaceAfter=12,
        leading=36,
    )
    cover_sub = ParagraphStyle(
        "CoverSub",
        parent=styles["Normal"],
        fontSize=11,
        textColor=BRAND_GRAY,
        spaceAfter=6,
    )
    h1 = ParagraphStyle(
        "H1",
        parent=styles["Heading1"],
        fontSize=16,
        textColor=BRAND_ACCENT,
        spaceBefore=24,
        spaceAfter=8,
        borderPad=4,
    )
    body = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        textColor=colors.HexColor("#1f2937"),
        spaceAfter=8,
    )
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=BRAND_GRAY,
        alignment=1,  # center
    )

    story: list[Any] = []

    # ── Cover page ────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph(title, cover_title))
    story.append(Spacer(1, 0.2 * inch))
    if generated_for:
        story.append(Paragraph(f"Prepared for: {generated_for}", cover_sub))
    if is_preview:
        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph(
            "⚠ This is a free preview. Subscribe at build-block.com for the full plan.",
            ParagraphStyle("Warn", parent=cover_sub, textColor=BRAND_ACCENT, fontSize=10),
        ))
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Generated by Build-Block · build-block.com", footer_style))
    story.append(PageBreak())

    # ── Sections ──────────────────────────────────────────────────────────
    ordered_keys = [k for k in SECTION_ORDER if k in sections]
    # Append any keys not in the fixed order
    ordered_keys += [k for k in sections if k not in ordered_keys]

    for key in ordered_keys:
        text = sections[key]
        if not text or not text.strip():
            continue
        section_title = SECTION_TITLES.get(key, key.replace("_", " ").title())
        story.append(Paragraph(section_title, h1))
        # Preserve paragraphs
        for para in text.split("\n\n"):
            para = para.strip()
            if para:
                story.append(Paragraph(para.replace("\n", " "), body))
        story.append(Spacer(1, 0.1 * inch))

    canvas_class = _make_canvas_class(watermark)
    doc.build(story, canvasmaker=canvas_class)
    return buf.getvalue()
